name = "lapce-terraform-ls"
version = "0.0.1+terraform-ls.0.32.7"
author = "panekj"
display-name = "Terraform (terraform-ls)"
description = "Terraform support for Lapce"
wasm = "lapce-terraform-ls.wasm"
icon = "terraform-vertical-color.svg"

[activation]
language = ["terraform"]
workspace-contains = [
  "*/*.tf",
  "*/*.tfvars",
]

[config."volt.serverPath"]
default = ""
description = "Path to custom terraform-ls server"

[config."volt.serverArgs"]
default = []
description = "Custom arguments for terraform-ls server"

[config."terraform.logFilePath"]
default = ""
description = """
Path to a file for Terraform executions to be logged into (`TF_LOG_PATH`) with support for variables (e.g. Timestamp, Pid, Ppid) via Go template syntax `{{.VarName}}`
"""

[config."terraform.timeout"]
default = ""
description = ""

[config."terraform.path"]
default = ""
description = """
Path to the Terraform binary.
This is usually looked up automatically from `$PATH` and should not need to be specified in majority of cases. Use this to override the automatic lookup.
"""

[config."indexing.ignorePaths"]
default = []
description = ""

[config."indexing.ignoreDirectoryNames"]
default = []
description = ""

[config."commandPrefix"]
default = ""
description = ""

[config."ignoreSingleFileWarning"]
default = false
description = ""

[config."experimentalFeatures.validateOnSave"]
default = false
description = ""

[config."experimentalFeatures.prefillRequiredFields"]
default = false
description = ""
